clusterGroup:
  name: hub

  namespaces:
    - istio-system
    - istio-cni
    - ztunnel
    # - tempo
    # - openshift-tempo-operator:
    #     operatorGroup: true
    #     targetNamespaces:
    # - openshift-opentelemetry-operator:
    #     operatorGroup: true
    #     targetNamespaces:
    - bookinfo:
        labels:
          istio.io/dataplane-mode: ambient

  subscriptions:
    servicemesh:
      name: servicemeshoperator3

    kiali:
      name: kiali-ossm

    # tempo:
    #   name: tempo-product
    #   namespace: openshift-tempo-operator

    # opentelemetry:
    #   name: opentelemetry-product
    #   namespace: openshift-opentelemetry-operator

  projects:
    - servicemesh
    - bookinfo
    # - distributed-tracing

  applications:
    ambient-servicemesh:
      name: ambient-servicemesh
      namespace: istio-system
      project: servicemesh
      path: ambient-servicemesh

    bookinfo:
      name: bookinfo
      namespace: bookinfo
      project: bookinfo
      path: bookinfo
