clusterGroup:
  name: hub

  namespaces:
    - istio-system
    - istio-cni
    - ztunnel
    - tempo
    - openshift-tempo-operator:
        operatorGroup: true
        targetNamespaces:
    - openshift-opentelemetry-operator:
        operatorGroup: true
        targetNamespaces:
    - bookinfo:
        labels:
          istio.io/dataplane-mode: ambient
    - openshift-cluster-observability-operator:
        operatorGroup: true
        targetNamespaces:

  subscriptions:
    servicemesh:
      name: servicemeshoperator3

    ossmc:
      name: kiali-ossm

    distributed-tracing:
      name: tempo-product
      namespace: openshift-tempo-operator

    opentelemetry:
      name: opentelemetry-product
      namespace: openshift-opentelemetry-operator

    cluster-observability:
      name: cluster-observability-operator
      namespace: openshift-cluster-observability-operator

  projects:
    - servicemesh
    - bookinfo
    - ossmc
    - distributed-tracing

  applications:
    ambient-servicemesh:
      name: ambient-servicemesh
      namespace: istio-system
      project: servicemesh
      path: ambient-servicemesh

    ossmc:
      name: ossmc
      namespace: istio-system
      project: ossmc
      path: ossmc

    distributed-tracing:
      name: distributed-tracing
      namespace: tempo
      project: distributed-tracing
      path: distributed-tracing

    bookinfo:
      name: bookinfo
      namespace: bookinfo
      project: bookinfo
      path: bookinfo
