apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
spec:
  version: v1.24.3
  namespace: istio-system
  values:
    meshConfig:
      enableTracing: true
      extensionProviders:
      - name: otel
        opentelemetry:
          port: 4317
          service: dev-collector.tempo.svc.cluster.local
      discoverySelectors:
        - matchLabels:
            istio-discovery: enabled
