apiVersion: v1
kind: Secret
metadata:
  name: tempostack-dev-minio
  namespace: tempo
type: Opaque
stringData:
  bucket: "tempo-data"
  endpoint: "http://minio:9000"
  access_key_id: "minio"
  access_key_secret: "minio123"
